language: "perl"

perl:
  - "5.10"

dist: trusty
sudo: required
services:
  - docker

install:
    - docker pull ensemblorg/ensembl-hive-htcondor
    - env

script:
    - docker run -v /home/travis:/home/travis ensemblorg/ensembl-hive-htcondor /home/travis/build/Ensembl/ensembl-hive-htcondor/travisci/setup_docker_and_run_tests.sh

