language: "perl"

perl:
  - "5.10"

sudo: required
services:
  - docker

install:
    - pushd scripts/docker-htcondor
    - docker build -t docker-htcondor .
    - popd
    - git clone --depth 1 --branch master https://github.com/Ensembl/ensembl-hive
    - env

script:
    - docker run -v /home/travis:/home/travis docker-htcondor /home/travis/build/Ensembl/ensembl-hive-htcondor/travisci/setup_docker_and_run_tests.sh

