language: "perl"

perl:
  - "5.10"

sudo: required
services:
  - docker

install:
    - docker pull muffato/docker-htcondor
    - git clone --depth 1 --branch master https://github.com/Ensembl/ensembl-hive
    - env

script:
    - docker run -v /home/travis:/home/travis muffato/docker-htcondor /home/travis/build/muffato/ensembl-hive-htcondor/travisci/setup_docker_and_run_tests.sh

