services:
  - docker

install:
    - docker pull ensemblorg/ensembl-hive-htcondor
    - env

script:
    - docker run -v /home/travis:/home/travis ensemblorg/ensembl-hive-htcondor /home/travis/build/Ensembl/ensembl-hive-htcondor/travisci/setup_docker_and_run_tests.sh

notifications:
  slack:
    rooms:
      # coregithub
      - secure: ewouWxhMrUgttig05QS3LBUSYoCn0pWqARRc4sNa1R8XnUEdZ7r5hl5fT7e7MfYGNLm9QUzXJyXjvu1356C4iyLX8BX29S2/fm0gxelHz/ER1JAnq8vu4G6+HgGXvKJKc9oKvtq6Msc5lcONY7oxRPyy4TAjd0Xn8KFarjvHeB0JG+rMXrLs529J3VyJoRLMryeL4eT+zekH8V+nw39a0tweW8N0aYE0Fv8k15MNk4iHzF9L0onBKpszwP4CtS5jmr4AnD8QSj/7CYUiwiIy8lTeoeYX3Rs72YJkaqJC2x2KY3GxeYiqxikdKc4Y7gfq6nOewMMNiMgTROt3NwjJG5s0GqhM6eQf05m47+t4yTa1ddo8eYT13u0WnEUb7Z6QPVvuQxbjW4syP36c9+pSXNIGlrSAQX3xWgGcHJ29MzQlBZzHQFL2Y/1PocW9zGiex/fWExAywJcYo1bLdpI/wc3ODr3ZhqkHR7HKeKeWK0ETEwxFwhsIeCC93e5lXty2UiaOQR44ycFDq8MauRVL7i0lYj1kUSiYIpS3SggkNLTfPe3zkSu3SC0G371/As9rlEZQzQ6IpzkGp+de5xhCWn31MlPeg7JCqskRKjz9kkRlWIryD3EHU6XsAR0uKndJNV5rnmedgDq+FqRgiMJGJU4gXe10RNpmZT5EB7eK+CU=
      # ehive-commits
      - secure: DuwtTQZmL7CwmtbuzyH+8fYzDqVMkQ9XYwfLLe7Be8ngdjj31Pi/DWVl89Kn/pEvNJ6wIg328d2qWoVppQ5ovXWeTfmZK1dmATED8wFaJ0QWtNqROJC30KtlMFrotfOj0ZVx9JgMpF1jo9KQlRl8zRuISayUbuH0uh1nCbLU/aC8rL9D+rQW6492Dj5kKEkHgJPSotuWsjIFTjneMGsbUMVr4NNlu2cRolZL1Xy2LWyXC3q9+2a95bFXVcAGkK3Pozt+sRtVfzefoqbUReTk0a1pAGaW6SgkgLjKqmqTpYON6d0YkF8SIi7uYnkJeuWYHOcotHLttyltHGm+UEAeYI1dAPgkIazMn+HCMicrJBVRO10T0AWPl2776p+bMzLu/NyfVt7JPnFV33Z70ZHw3dXL0CK1Ba2Yjf+VAxB44d9kPD4s9JLimB/ds2/dpTkX7b1rNMWbiBNarsVTm8aL7813hUb0mGcVUoRMDjgD7NYhUhx50IKbcFJeOoMEShjrKLxe1ahStGGexPUaGDTyixNFw42Tm5VpjKYI8IFZNZrsFci/fG1qO+2ya0OBpw3bdK8sBGfRDPnexqJIpPA0j+LM9CyYXmgzCvORl76s+FYqqjD0qetkNKWM2xiMDIG8MFNqCSzxUssAC4jpzf+5ZHD7VQptvkg0AylI6vJwXSU=
    on_failure: change
