#!/bin/bash

read -r -d '' cq << "EOF"
1	0	condoradmin	1	long_mult-Hive-default-1
2	0	condoradmin	2	long_mult-Hive-default-1
3	0	condoradmin	4	tracking_homo_sapiens_funcgen_81_38_hive
3	1	condoradmin	1	tracking_homo_sapiens_funcgen_81_38_hive
4	1	condoradmin	2	long_mult-Hive-default-1
5	1	condoradmin	3	long_mult-Hive-default-1
6	1	otheruser	2	long_mult-Hive-default-1
6	0	otheruser	1	long_mult-Hive-default-2
7	0	otheruser	2	long_mult-Hive-default-2
8	0	condoradmin	2	long_mult-Hive-default-2
9	0	condoradmin	5	long_mult-Hive-default-2
10	0	condoradmin	6	long_mult-Hive-default-2
11	0	condoradmin	2	long_mult-Hive-default-2
11	1	condoradmin	1	long_mult-Hive-default-2
11	2	condoradmin	1	long_mult-Hive-default-2
11	3	condoradmin	2	long_mult-Hive-default-2
11	4	condoradmin	2	long_mult-Hive-default-2
11	5	condoradmin	2	long_mult-Hive-default-2
11	6	condoradmin	2	long_mult-Hive-default-2
11	7	condoradmin	2	long_mult-Hive-default-2
EOF

received="$*"
#lastarg=${received//^.*Env//}
lastarg=$(echo "$received" | sed "s/^.*''\s*//")

echo $lastarg >> RL
if [ "$lastarg" = "" ];
then
  echo "$cq"
else
  echo "$cq" | awk "\$3==\"$lastarg\" || (\$1 \".\" \$2)==\"$lastarg\""
fi

