name: Run the test suite
on:
  workflow_dispatch:
  push:
    paths:
      - modules/**
      - scripts/test-suite/**
      - t/**

jobs:
  run-tests:
    name: Run the test suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_TOKEN_UPLOAD_PACKAGE }}
          registry: ghcr.io
      - name: Pull the Docker image
        run: docker pull ghcr.io/muffato/ensembl-hive-htcondor:version-2.5
      - name: Run the test suite
        run: docker run -v $GITHUB_WORKSPACE:/repo/ensembl-hive-htcondor ghcr.io/muffato/ensembl-hive-htcondor:version-2.5 /repo/ensembl-hive-htcondor/scripts/test-suite/setup_docker_and_run_tests.sh
