name: Run the test suite
on:
  workflow_dispatch

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull the Docker image
        run: docker pull docker.pkg.github.com/muffato/ensembl-hive-htcondor/ensembl-hive-htcondor:version-2.5
      - name: Run the test suite
        run: docker run -v $GITHUB_WORKSPACE:/home/travis/build/Ensembl/ensembl-hive-htcondor /home/travis/build/Ensembl/ensembl-hive-htcondor/travisci/setup_docker_and_run_tests.sh
