name: Run the test suite
on:
  workflow_dispatch

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
  run_tests:
    name: Run the ensembl-hive-htcondor test suite
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/muffato/ensembl-hive-htcondor/ensembl-hive-htcondor
      options: "-v $GITHUB_WORKSPACE:/home/travis/build/Ensembl/ensembl-hive-htcondor"
    steps:
      - name: Run
        run: /home/travis/build/Ensembl/ensembl-hive-htcondor/travisci/setup_docker_and_run_tests.sh
